"""empty message

Revision ID: 0cbe3e88fcee
Revises: 35338bd26f30
Create Date: 2023-02-10 06:48:36.116119

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0cbe3e88fcee'
down_revision = '35338bd26f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aura', sa.String(length=50), nullable=True),
    sa.Column('exilus', sa.String(length=50), nullable=True),
    sa.Column('mod1', sa.String(length=50), nullable=True),
    sa.Column('mod2', sa.String(length=50), nullable=True),
    sa.Column('mod3', sa.String(length=50), nullable=True),
    sa.Column('mod4', sa.String(length=50), nullable=True),
    sa.Column('mod5', sa.String(length=50), nullable=True),
    sa.Column('mod6', sa.String(length=50), nullable=True),
    sa.Column('mod7', sa.String(length=50), nullable=True),
    sa.Column('mod8', sa.String(length=50), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('build')
    # ### end Alembic commands ###
