"""Added Mod, Warframe, WeaponPrimary

Revision ID: 35338bd26f30
Revises: d84dcd9dea4b
Create Date: 2023-02-09 23:29:47.404424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '35338bd26f30'
down_revision = 'd84dcd9dea4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mod',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('polarity', sa.String(length=20), nullable=False),
    sa.Column('drain', sa.Integer(), nullable=False),
    sa.Column('rank', sa.Integer(), nullable=False),
    sa.Column('rarity', sa.String(length=20), nullable=False),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('effect', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('warframe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('health', sa.Integer(), nullable=False),
    sa.Column('shield', sa.Integer(), nullable=True),
    sa.Column('armor', sa.Integer(), nullable=False),
    sa.Column('energy', sa.Integer(), nullable=True),
    sa.Column('starting_energy', sa.Integer(), nullable=True),
    sa.Column('sprint_speed', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('warframe')
    op.drop_table('mod')
    # ### end Alembic commands ###
